export const ErrorTypes = {
  // Authentication & Authorization (VERY common)
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_INVALID: "TOKEN_INVALID",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_BANNED: "ACCOUNT_BANNED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  // Validation (happens A LOT)
  VALIDATION: "VALIDATION",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK",

  // Data conflicts (very common)
  DUPLICATE: "DUPLICATE",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  DUPLICATE_USERNAME: "DUPLICATE_USERNAME",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  CONFLICT: "CONFLICT",

  // Not found (happens constantly)
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  // Database (frequent)
  DATABASE_ERROR: "DATABASE_ERROR",
  CONNECTION_FAILED: "CONNECTION_FAILED",
  QUERY_FAILED: "QUERY_FAILED",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",

  // Rate limiting & Quotas (important for production)
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",

  // File operations
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",

  // Network & External services
  NETWORK_ERROR: "NETWORK_ERROR",
  TIMEOUT: "TIMEOUT",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  EXTERNAL_API_ERROR: "EXTERNAL_API_ERROR",

  // Payment (if you have payments)
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",

  // Permissions & Access (common in multi-user apps)
  PERMISSION_DENIED: "PERMISSION_DENIED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  OWNER_ONLY: "OWNER_ONLY",

  // Operations
  OPERATION_FAILED: "OPERATION_FAILED",
  DELETE_FAILED: "DELETE_FAILED",
  UPDATE_FAILED: "UPDATE_FAILED",
  CREATE_FAILED: "CREATE_FAILED",

  // Bad requests (common)
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_FORMAT: "INVALID_FORMAT",
  MALFORMED_DATA: "MALFORMED_DATA",

  // Catch-all
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  SERVER_ERROR: "SERVER_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const

export type ErrorType = (typeof ErrorTypes)[keyof typeof ErrorTypes]